# serverless.yml

service: invrtir-grafico-no-lineal-cripto-lp

provider:
  name: aws
  runtime: nodejs14.x
  stage: proy
  region: us-east-2

functions:
  app:
    handler: index.handler
    events:
      - http: GET /
      - http: 'GET {proxy+}'